### ISSUE TITLE
Add support for exporting the writers listed in the credits please

### ISSUE THREAD

**Issue by andredelaney** [watsonbox/exportify#100]
This would be amazing

**Comment by watsonbox** [comment]
I'm afraid that won't be possible since this data isn't available via the [web API](https://developer.spotify.com/documentation/web-api/reference/):

* https://community.spotify.com/t5/Spotify-for-Developers/Getting-credits-on-a-track/td-p/4950934
* https://github.com/spotify/web-api/issues/779

**Comment by matthiasstraka** [comment]
When using the Spotify web-client, the website requests credits through https://spclient.wg.spotify.com/track-credits-view/v0/experimental/{id}/credits but when requesting with the standard WebAPI authorization token, you get a 403 error code "Client not allowed". It works with the token from the current web-session though (use the Developer-Tools of your browser to get to them).
