### ISSUE TITLE
Exporting playlists created by me in bulk

### ISSUE THREAD

**Issue by rsapkf** [watsonbox/exportify#101]
Would it be possible to add support for allowing export of all playlists created by _me_ in bulk and exclude playlists from other users that are in my library?

**Comment by watsonbox** [comment]
I'll leave it here for consideration 👍

**Comment by watsonbox** [comment]
Implemented in #171 - [usage details here](https://github.com/watsonbox/exportify?tab=readme-ov-file#advanced-search-syntax).
