### ISSUE TITLE
Add field to CSV to label unavailable tracks

### ISSUE THREAD

**Issue by rsomervail** [watsonbox/exportify#108]
Would it be possible to add a field to the csv output file which marks whether a track is unavailable to play in spotify?

This would be very useful for a script I'm running which uses the csv output.

**Comment by golanremi** [comment]
I totally agree, that would help a lot in trying to find alternatives to these unavailable songs. In a very large playlist, it is impossible to track them.
Thank you

**Comment by watsonbox** [comment]
✅
