### ISSUE TITLE
Migrate app to GitHub Pages of similar

### ISSUE THREAD

**Issue by JMPerez** [watsonbox/exportify#11]
I think you could use GitHub pages very easily to serve the project as a website. Create a `gh-pages` branch and then you will be able to access the site browsing https://watsonbox.github.io/exportify
In fact, you could then remove the `master` branch and leave `gh-pages` as the default one.

**Comment by watsonbox** [comment]
Thanks for the suggestion.  It's true that this would remove the need for rawgit, but would it provide any other advantages over what is already in place?  Perhaps a slightly nicer URL?

**Comment by JMPerez** [comment]
You wouldn't depend on rawgit (that seems to have some [reliability issues](https://groups.google.com/forum/#!topic/cornerstone-platform/SNQnoYH75oQ), you get built-in CDN, a nicer URL (although the URL could be simpler if you use `index.html` instead of `extendify.html`) and you would use what most developers are using to serve static websites hosted on GitHub.

Still, just wanted to let you know that GitHub Pages was a thing.

**Comment by NicoWeio** [comment]
Update: rawgit.com is about to die (see their home page). This is a good opportunity to do the migration to GitHub Pages.

**Comment by pavelkomarov** [comment]
I second Nico. Rawgit is losing support. This issue needs to be addressed so the service can continue to live.

**Comment by watsonbox** [comment]
Thanks for the tips. I did implement this as a [Github Pages deployment step on Travis](https://docs.travis-ci.com/user/deployment/pages/), and updated the `README` with the new URL. I took measures to make sure that the old URL still works too, just in case some people are still using that.
