### ISSUE TITLE
Add support for importing an exported playlist

### ISSUE THREAD

**Issue by donalmurtagh** [watsonbox/exportify#130]
According to the docs

> it's also pretty straightforward to re-import them into Spotify. Open up the CSV file in Excel, for example, select and copy the spotify:track:xxx URIs, then simply create a playlist in Spotify and paste them in.

Assuming Spotfiy's API supports creating playlists, it should be possible to automate this.

**Comment by watsonbox** [comment]
I'm afraid although I did add that as a small tip to the docs, _importing_ is outside the scope of this project. If nothing else it would cause big problems for its name.

**Comment by donalmurtagh** [comment]
It seems fairly pointless to export data unless there's also a means of importing it. Whoever heard of a backup tool without a corresponding restore tool?
