### ISSUE TITLE
misleading info in README for re-importing playlists?

### ISSUE THREAD

**Issue by owocado** [watsonbox/exportify#134]
Hi,

firt, thank you a ton for making this tool. Its immensely helpful for what I wanted.
Now that I exported my playlists with this, I want to import the exported tracks back to a new playlist in my other Spotify acount. I can see in repo README, it explains how to re-import the data but it sounds kinda misleading as it says to open the exported CSV file in Excel, select and copy all `spotify:track:xxxx` URIs and paste it into the new playlist I created on Spotify but it does not seem to be working, at least for me. When I paste those URIs into an empty Spotify playlist, nothing happens at all. I have tried few times but same thing.

Does the said section of README need to be updated with the method it explains?

**Comment by egliorn** [comment]
Hi @o-wo 
This only seems to work on the Spotify desktop app.
It doesn't work for me on the web either.

**Comment by watsonbox** [comment]
Thanks for the comment about this process with the web app. I updated the `README` to clarify 👍 .
