### ISSUE TITLE
Letters are turning into symbols

### ISSUE THREAD

**Issue by golanremi** [watsonbox/exportify#141]
Thank you for this excellent tool.
One of my playlists has song names with Hebrew letters. When exporting this playlist, the Hebrew letters turn into symbols like the below examples:
◊§◊†◊° ◊î◊®◊ó◊ï◊ë (◊û◊ô◊©◊î◊ï ◊î◊§◊°◊ô◊ß ◊ê◊™ ◊î◊ñ◊®◊ù) 
◊§◊†◊ß◊° ◊î◊ß◊ò◊ü◊
¶◊ô◊§◊ï◊® ◊ß◊ò◊†◊î 
◊ë◊ú◊ë◊©◊ë◊ó◊ô ◊û◊¢◊ï◊ñ

Can this be fixed?

Thank you

**Comment by watsonbox** [comment]
You might find this comment useful https://github.com/watsonbox/exportify/issues/145#issuecomment-1704281615.
