### ISSUE TITLE
Processing liked songs

### ISSUE THREAD

**Issue by smxko** [watsonbox/exportify#151]
Hi,

keeping the limitations of the Spotify API in mind, is it possible to process my „liked songs“ the same as a playlist? Currently, I have to paste all my 3k+ liked songs into a temporary playlist to be backed up by Exportify. This works well enough, only downside is that the date added information on the songs is lost because it obviously uses the date I temporarily added them into the playlist and not the date I added them to my liked songs.

Regards

**Comment by watsonbox** [comment]
Exportify does support liked songs, as per the screenshot in the `README`:

<img src="https://raw.githubusercontent.com/watsonbox/exportify/b4727473583b31e14cf444d71bea2cacd1851469/screenshot.png"/>
