### ISSUE TITLE
Page is blank after clicking on get started (Bug)

### ISSUE THREAD

**Issue by YouSureKimmich** [watsonbox/exportify#156]
After clicking on get started, the page is blank. This issue has just begin today as I have used the app several times previously and did not face the issue. I have tried logging out and re logging (giving access to my spotify account) twice but to no success. 

![image](https://github.com/watsonbox/exportify/assets/164650645/9c61d264-1161-4a82-a192-739046faefcf)

**Comment by JRodster** [comment]
Same, I've also tried with multiple browsers and multiple devices, and all of them have gotten stuck at the blank page.

**Comment by YouSureKimmich** [comment]
@JRodster I have found an alternative site which does somewhat similar job in exporting. Check it out https://www.tunemymusic.com/

**Comment by JRodster** [comment]
@YouSureKimmich Been using multiple services concurrently for some time now, with Exportify being one of them.

There's also [Spotify-Backup](https://www.spotify-backup.com/) for individual public playlists, [SpotMyBackup](http://www.spotmybackup.com/) for an account-wide backup, and [Skiley](https://skiley.net/) for occasional playlist exports and additional tools.

**Comment by YouSureKimmich** [comment]
Will check those out! Thanks for sharing the alternatives. If you have any other alternatives apart from the ones mentioned above then please do share it. The sites which help in exporting to CSV file in one go are useful for me

**Comment by JRodster** [comment]
@YouSureKimmich Exportify's working for me again! Just wanted to let you know in case you hadn't already noticed (I just noticed now).

**Comment by JRodster** [comment]
Huh, weird. I wonder what's been causing this bug in the first place.

@YouSureKimmich Have you tried removing Exportify's access permissions from your Spotify account (in the "Manage Apps" page) before logging out and logging back in through Exportify's webpage? Maybe resetting permissions on Spotify's end like that might help.

Don't think there's anything else I've done differently from you before Exportify ended up fixing itself for me. Don't remember if I cleared any saved site settings from Exportify's webpage (cookies, etc.), don't think I did?

**Comment by YouSureKimmich** [comment]
@JRodster Yea I have tried that twice now. I have even cleared all cache, cookies from my browser however the issue persists. Its the same with Edge browser too.

**Comment by theotherbrandonsoto** [comment]
Following up on this- I am experiencing the same issue. I have also tried in multiple browsers, and removed the permissions then re-added them on Spotify as well. 

No luck! Will try some of the other tools

**Comment by YouSureKimmich** [comment]
@theotherbrandonsoto Following up with a positive update- The issue seems to have resolved on its own. Surprisingly. Will continue to use it and update if changes

**Comment by watsonbox** [comment]
> The issue seems to have resolved on its own.

Actually, I made an [experimental fix](https://github.com/watsonbox/exportify/commit/84b826d9838a5a45f5aef7745c18e9a9b41af41e) about 3 hours ago. Glad to hear it seems to work!

**Comment by YouSureKimmich** [comment]
@watsonbox Thank you so much Howard! Appreciate the work you have done on this webpage. Makes thing super easy for users like me to have a backup especially in a detailed csv file for excel use. 

Also, by any chance, do you have any sites or something similar to the one you have for spotify to transfer playlist between spotify to youtube music?

I have tried Tunemymusic but the free version has limited number of songs (500) which get transferred

**Comment by watsonbox** [comment]
> Appreciate the work you have done on this webpage.

Thanks 🙂 

> Also, by any chance, do you have any sites or something similar to the one you have for spotify to transfer playlist between spotify to youtube music?

I'm afraid not. I don't use YouTube Music.

**Comment by YouSureKimmich** [comment]
> > Appreciate the work you have done on this webpage.
> 
> Thanks 🙂
> 
> > Also, by any chance, do you have any sites or something similar to the one you have for spotify to transfer playlist between spotify to youtube music?
> 
> I'm afraid not. I don't use YouTube Music.

@watsonbox Okay no worries. Thank you once again!
