### ISSUE TITLE
Exporting all playlists with same names

### ISSUE THREAD

**Issue by morganbarrett** [watsonbox/exportify#157]
Exporting all playlists with multiple playlists of the same name, will only export one of the playlists, it should export all of them. This seems to be because the exported zip contains files named after the playlists, I propose adding some sort of id (playlist id, or just an incrementing number) to differentiate playlists of the same name.

**Comment by pavelkomarov** [comment]
I solved this in my version with a while loop:

```javascript
let csv = await this.csvData(access_token, playlist)
let fileName = this.fileName(playlist)
while (zip.file(fileName + ".csv")) { fileName += "_" } // Add underscores if the file already exists so playlists with duplicate names don't overwrite each other.
zip.file(fileName + ".csv", csv)
```

**Comment by watsonbox** [comment]
✅
