### ISSUE TITLE
Playlist sort order and search

### ISSUE THREAD

**Issue by janpalmen** [watsonbox/exportify#158]
Hi! Thanks for a great service :-)

Recently the sort order of the playlists changed. How are they sorted now? Is it possible to sort them in other ways, like name? I have trouble finding some of my playlists when to export them. I have tried to use the search box but that is not working at all. Any suggestions on this?

**Comment by janpalmen** [comment]
Today the sort order was the same as in spotify. Thanks a lot :-)

**Comment by watsonbox** [comment]
I haven't changed anything, but I'm glad to hear your issue is resolved 🙂. Much of Exportify's functionality comes from the Spotify APIs, so when they change or break, so does this app.
