### ISSUE TITLE
Export hangs

### ISSUE THREAD

**Issue by alchokem** [watsonbox/exportify#159]
Exporting All playlists hangs and never completes

URL: https://watsonbox.github.io/exportify/#access_token=BQDVzKbfGDEWybV74PfhDFTji0T9vX9rof7NC3NsXb0-tlOEC6hBOP5xqFkBkn8JpVDD8kaJrcNB0wfoNHUOCDyGG-hnqKD1NaXZFZnnOKHiO5p1c_Jq0P3DkAAVLMbiWbq2h14sqyf2dTqQe56ENp8FO-P7zhxVxUaO6wsFvkGro3DxFRH8ni9lCux-z1e3gZZfKoc&token_type=Bearer&expires_in=3600

**Comment by rodanman** [comment]
Bumped, doesn't work anymore. Always seemed to get to about 80% and then hangs forever.

I've tried removing playlists thinking that I'm making the "work load" less and hoping it works with a smaller amount of lists, but I can't ever get it to complete the All export.

**Comment by LucasZamprogno** [comment]
It could be extensions. I checked my network requests when loading the page, and some of the calls were being blocked by Privacy Badger.

**Comment by alchokem** [comment]
A month later. Still not working. Ran it in a browser with all extensions disabled.  Still doesn't work.

**Comment by abstrnoah** [comment]
Same issue still on Chrome, Firefox, and Qutebrowser with all extensions disabled. It would be cool if this were fixed.

**Comment by watsonbox** [comment]
Could anyone having this issue please let me know if it's working now? I think it might have had the same root cause as https://github.com/watsonbox/exportify/issues/156.

**Comment by LucasZamprogno** [comment]
Working for me now 👍
