### ISSUE TITLE
Encountered TypeError: Cannot read properties of null (reading 'id').

### ISSUE THREAD

**Issue by GitHunter0** [watsonbox/exportify#161]
Hi folks, I'm receiving this error message:

```
Couldn't export MY_PLAYLIST_NAME with id 2AIVHBy6UpE62UQ5Mzwhhs. Encountered TypeError: Cannot read properties of null (reading 'id').
```

May it be caused by special japanese characters in my playlist?

Thank you

**Comment by GitHunter0** [comment]
The issue was that Exportify can't handle podcasts and there was a song that was in podcast type, so the workaround is to remove it from the playlist. 

See https://github.com/pavelkomarov/exportify/issues/30

**Comment by watsonbox** [comment]
Please see https://github.com/watsonbox/exportify/issues/87#issuecomment-740586642 - the repository/version you link is not my own, so you should raise this issue there. I fully accept and agree that it's confusing/frustrating for users, but unfortunately there's nothing I can do about that.

**Comment by GitHunter0** [comment]
Thank you, @watsonbox . As an unrelated question, do you plan to enable the backup of the playlist **description** and **cover image**?

**Comment by watsonbox** [comment]
> As an unrelated question, do you plan to enable the exportation of the playlist description and cover image?

No, I'm afraid not. At least not before different output formats are implemented, and I've no immediate plans to work on that.

**Comment by GitHunter0** [comment]
@watsonbox , it would be really handy to have that, but I appreciate your feedback, exportify is still a great tool.
