### ISSUE TITLE
Add Genre and Original Album release year to export

### ISSUE THREAD

**Issue by syedmahm** [watsonbox/exportify#17]
Hello, Thanks for building such a great way of exporting the spotify playlist tracks. I have a couple of requests, I don't know if I am requesting at the right place. Is there anyway to get **Genre *_and *_Original Album release year** information for the tracks? I would love to see these two information. Thanks again for your great product!

**Comment by oletho** [comment]
I second that. I wish to export a very large playlist, sort it by Release Year and do an import to create a new playlist on Spotify. This tool is great but unfortunately no Year :)

**Comment by pavelkomarov** [comment]
My version has these things and more.

[It lives here](https://pavelkomarov.com/exportify/app.html)

**Comment by watsonbox** [comment]
👍  Added to master issue here https://github.com/watsonbox/exportify/issues/67

Thanks @pavel-aicradle for your efforts 🙏 .
