### ISSUE TITLE
Export Shows Similar Songs as Duplicates when they actualy are not

### ISSUE THREAD

**Issue by bsper** [watsonbox/exportify#181]
Seeing an issue where the Exportify export will lump similar songs as the same when they are technically different tracks according to Spotify.

For example, I have a playlist with these two songs:
| Song Name | Album | Spotify URL
| --- | --- | --- |
| Kashmir - 1990 Remaster | Physical Graffiti (1994 Remaster) | https://open.spotify.com/track/2nVHqZbOGkKWzlcy1aMbE7?si=5fdb9a230c7f42b6
| Kashmir - Remaster | Physical Graffiti (Deluxe Edition) | https://open.spotify.com/track/6Vjk8MNXpQpi0F4BefdTyq?si=8e1fd5dc174d408e |

But when Exportify exports the playlist it just lists both songs as `spotify:track:6Vjk8MNXpQpi0F4BefdTyq`, so it thinks both are from the Album 'Physical Graffiti (Deluxe Edition)'

I have about 5 others songs that have similar issues and can list them out if it helps.

Don't know exactly when this behavior started, but it was not happening when I did a backup on 08/04/2024, but then it started when I did my next backup on 09/02/2024

**Comment by watsonbox** [comment]
You're quite right.. thanks for the report and very clear repro data. It came in as part of the changed `is_market` behavior in https://github.com/watsonbox/exportify/commit/9b0f396cb420e29b28857905db99f1aeb4c108d8. I've reverted that update for now to correct this bug, until I have time to see if it can be re-introduced without the same problem.
