### ISSUE TITLE
More of a question than an issue

### ISSUE THREAD

**Issue by 12nick12** [watsonbox/exportify#25]
Is there a way to export my music? http://imgur.com/a/nBFcZ

**Comment by Transrian** [comment]
You just got to put all the songs you like into a new temporary playlist, with CTRL-A + drag and drop, and it will work

**Comment by ocram** [comment]
See https://github.com/watsonbox/exportify/pull/37

**Comment by watsonbox** [comment]
Thanks @ocram and sorry for the delay. I'm currently reviewing all issues and will do my best to take a look at your PR when I get to this one 🙏 .

In the meantime I propose that we capture this requirement in this master issue: https://github.com/watsonbox/exportify/issues/18.
