### ISSUE TITLE
I try to open the exportify and get this - Your access to this site has been restricted. If you believe this is an error, please contact the Support Team.

### ISSUE THREAD

**Issue by orange109** [watsonbox/exportify#26]
Your access to this site has been restricted.

If you believe this is an error, please contact the Support Team.

Is everyone getting this? please help

**Comment by jonascj** [comment]
Works flawlessly for me (https://rawgit.com/watsonbox/exportify/master/exportify.html)
Where is this error coming from, your browser, some weird website, Windows 10?
Some more details are needed to help you I believe.

**Comment by orange109** [comment]
Hello,

It's working again for me now as well..

I guess there was an issue for a short time.

Thanks anyway
