### ISSUE TITLE
"hh:mm:ss" format instead "Track Duration (ms)"

### ISSUE THREAD

**Issue by soycd** [watsonbox/exportify#27]
Exportify works great, thanks!

Would it be possible to make the export to .xlsx or .ods format with "hh:mm:ss" format instead "Track Duration (ms)"?

I usually add a "hh:mm:ss" column to the spreadsheet the following way:

Add a column with the following function and set its Format to "Time":

=G2/86400000

Or add a column with the following function: 

=TIME(0;TRUNC(G2/1000/60);ROUND((MOD(G2/1000/60;1))*60;0))

**Comment by jsejcksn** [comment]
@soycd Yes, it is possible. Just fork the repo and you can make those changes.

**Comment by watsonbox** [comment]
I would suggest exporting data and then making this transform in your favorite spreadsheet app.
