### ISSUE TITLE
Exporting the Songs Playlist

### ISSUE THREAD

**Issue by Ordowix** [watsonbox/exportify#39]
![image](https://user-images.githubusercontent.com/29491308/38649200-88d276cc-3db2-11e8-857a-5d391239c8aa.png)
In case of confusion.

This is not an available selection and it's the only one I need. I use the dates on the songs as a reference for Spotify, which I dually use as "music journal."

As a novice, I cannot contribute via fork or create my own Spotify app alone.
![image](https://user-images.githubusercontent.com/29491308/38649308-13b8b33c-3db3-11e8-9195-cf9167eaf7ea.png)

**Comment by JanJastrow** [comment]
Maybe try the [fork ](https://github.com/delight-im/exportify)from @delight-im, which is exporting also the/all songs in your library.
https://rawgit.com/delight-im/exportify/master/exportify.html

**Comment by Ordowix** [comment]
Works great. Thank you.

From,
J. Blake Smith

**Comment by watsonbox** [comment]
Thanks for raising this. Closing as it is covered by this issue: https://github.com/watsonbox/exportify/issues/18
