### ISSUE TITLE
Export all fails on Safari 7.1.2: "Failed to load resource: Frame load interrupted"

### ISSUE THREAD

**Issue by watsonbox** [watsonbox/exportify#4]

**Comment by kdawgwilk** [comment]
same here in safari 9

**Comment by gokayokutucu** [comment]
...and on safari version 13.1 (15609.1.20.111.8) too.

**Comment by watsonbox** [comment]
This issue is [fixed](https://github.com/eligrey/FileSaver.js/issues/215) since Safari 10.1.
