### ISSUE TITLE
Fix crashes on certain playlists

### ISSUE THREAD

**Issue by simoncarbajal** [watsonbox/exportify#48]
I click in "Export All" button but nothing happens...

**Comment by pitastrudl** [comment]
Same here, this is what the console gives me in chrome 70: 
```

exportify.js:310 Uncaught TypeError: Cannot read property 'total' of null
    at Object.csvData (<anonymous>:310:51)
    at Object.<anonymous> (<anonymous>:278:49)
    at Function.each (jquery.js:374)
    at n.fn.init.each (jquery.js:139)
    at Array.<anonymous> (<anonymous>:276:22)
    at Array.<anonymous> (jquery.js:3256)
    at j (jquery.js:3099)
    at Object.fireWith [as resolveWith] (jquery.js:3211)
    at Object.<anonymous> (jquery.js:3339)
    at j (jquery.js:3099)
```

**Comment by sunscreem** [comment]
Same issue here :(

**Comment by jessebett** [comment]
I also have this issue.

**Comment by sunscreem** [comment]
Does this project look likes the owner isn't updating it any more do we think?

**Comment by C-Kenny** [comment]
Export All button still errors out

```
Uncaught TypeError: Cannot read property 'total' of null
    at Object.csvData (<anonymous>:310:51)
    at Object.<anonymous> (<anonymous>:278:49)
    at Function.each (jquery.js:374)
    at n.fn.init.each (jquery.js:139)
    at Array.<anonymous> (<anonymous>:276:22)
    at Array.<anonymous> (jquery.js:3256)
    at j (jquery.js:3099)
    at Object.fireWith [as resolveWith] (jquery.js:3211)
    at Object.<anonymous> (jquery.js:3339)
    at j (jquery.js:3099)
```

**Comment by honestabe10** [comment]
Having the same problem

**Comment by ocram** [comment]
It seems that the fix from [this pull request](https://github.com/watsonbox/exportify/pull/44) may have to be applied in the `PlaylistsExporter` as well.

Until this is fixed, you can find a working version in [our fork](https://github.com/delight-im/exportify).

**Comment by pavelkomarov** [comment]
I believe [this is the problem](https://github.com/pavelkomarov/exportify/issues/10). My version has some architecture to catch these errors so the rest of the playlists still get downloaded. Right now only zipping 20 at a time, not truly *all* a user's playlists.

[use here](https://pavelkomarov.com/exportify/app)

**Comment by watsonbox** [comment]
I [reverted the starred tracks functionality](https://github.com/watsonbox/exportify/commit/f42f74314880d15bdb373228fed5508cc25be831) which I believe is part of the solution to this.

**Comment by watsonbox** [comment]
I believe this one is now fixed

**Comment by sunscreem** [comment]
Hey @watsonbox 

![image](https://user-images.githubusercontent.com/7523595/99824584-d02cb880-2b4d-11eb-80f2-96e6079a4b6d.png)


Thank you sir. All working again for me :)

**Comment by watsonbox** [comment]
Glad to hear it! 2020 seems to be a good year for top tunes 😁 .

**Comment by sunscreem** [comment]
haha - for my music taste (trance and progressive house) it's been an outstanding year. All the DJ's and producers being stuck at home has meant this has been some of the most amazing music I've heard in my entire 46 years. I guess I should really trim that back though. It's supposed to be a top 10. Not a top 67.
