### ISSUE TITLE
How to export playlists to CSV with a different column order?

### ISSUE THREAD

**Issue by Acrossf** [watsonbox/exportify#54]
The CSV files have the column order A = Title B = Artist, but is it possible to reverse the order in the code self without adjusting that afterward in Excel? In other words, I want to create CSV files that already has the order Artist - Title instead.

**Comment by watsonbox** [comment]
It would be possible in theory, but in practice everyone is going to have different views on what the ordering should be, so I'd rather leave that to be solved as an after-export processing step.

Put another way, this seems to be almost a presentational request, which is not what I'm considering "in scope" for this project.
