### ISSUE TITLE
can the list of albums be exported as well?

### ISSUE THREAD

**Issue by horizonbrave** [watsonbox/exportify#57]
Hi, I'd love please to backup not only the playlists content but also the full list of albums present in my library. Thanks

**Comment by pavelkomarov** [comment]
In principle yes. My version gathers information from playlist, song, and artist json. querying for album json is just another wave of traffic.

[open an issue over here](https://github.com/pavelkomarov.com/exportify/issues), and I'll think about implementing it.

[exportify.net](https://exportify.net)

**Comment by watsonbox** [comment]
Let's pick this up in the master issue 👍  https://github.com/watsonbox/exportify/issues/18
