### ISSUE TITLE
Export track year and genre columns

### ISSUE THREAD

**Issue by pavel-aicradle** [watsonbox/exportify#59]
I'm trying to do some analysis on my music tastes. I'll probably publish the script soon so you all can use it. It would be really nice to be able to breakdown a playlist by the release year of the songs and by the genres they fall in to. As is, these columns aren't provided, so I'm looking at having to query spotify with the track URIs, retrieve JSON, and parse out the pieces of info I need through [these server calls](https://developer.spotify.com/console/get-track).

Note: Getting release year is included in the track's JSON, but genre information is found only in the artist's JSON. Thankfully the track has an artist URI associated with it, but it means you'll have to make a second call [of this form](https://developer.spotify.com/console/get-artist/).

**Comment by pavelkomarov** [comment]
I've implemented a [version that does this](https://github.com/pavelkomarov/exportify/blob/master/exportify.js). Hopefully studying it can be helpful toward improving this repo, but I've opted not to make a PR of my own; the changes are too extensive.

Here's my analysis notebook, in case anyone wants to do something similar on their own lists: https://github.com/pavelkomarov/exportify/blob/master/taste_analysis.ipynb

**Comment by watsonbox** [comment]
👌 Added to a master issue https://github.com/watsonbox/exportify/issues/67

Thanks @pavel-aicradle for your work on this and super cool Jupyter analysis 🙂
