### ISSUE TITLE
Not all table rows same width

### ISSUE THREAD

**Issue by pavel-aicradle** [watsonbox/exportify#60]
In exporting a grand playlist of mine I found I couldn't `.read_csv` in python because the `.csv` came out mangled. I was able to go through it to find out what was going on: In some cases fields are missing, and then JavaScript seems to move all cells rightward of that one left to fill the gap. In other cases something like an album name can be *really* long, and it runs over in to the next cell for some reason, pushing everything to the right rightward.

**Comment by pavelkomarov** [comment]
I fixed it. Problem was related to commas and quotes being in the song titles and album names. Some regex to remove all the quotes fixed the problem.

[Code here](https://github.com/pavelkomarov/exportify/blob/master/exportify.js)
[Live version (with other improvements) here](https://pavelkomarov.com/exportify/app)

**Comment by watsonbox** [comment]
Thanks a lot for raising this and for working on this topic 🙏 . I agree it's a pain and needs fixing.

I think it's the same issue as this one which was previously raised, so I'll use that one as the master: https://github.com/watsonbox/exportify/issues/8.
