### ISSUE TITLE
Add logout facility

### ISSUE THREAD

**Issue by ghost** [watsonbox/exportify#61]
good evening
how can I log out from exportify? For me would be useful.

**Comment by pavelkomarov** [comment]
My version supports this.

[exportify.net](https://exportify.net)

**Comment by watsonbox** [comment]
I've had a think about this and done some digging, and I'm not persuaded that it's really possible to do what I believe is called for by this feature. I take logging out to mean closing the session - i.e. deauthorizing the access token.

To illustrate using @pavel-aicradle's approach: log in and duplicate the tab. Log out in one of the tabs. It's still possible to continue to use the other until the access token expires.

However, the practical purpose of this feature could be to change user, which is possible as [described here](https://stackoverflow.com/a/24611621). I think a good solution here would therefore be to have a logout link which re-directs to the login screen with some explanation of the "Not you?" option and then forces a permissions request with `show_dialog=true`.

**Comment by watsonbox** [comment]
Done!
