### ISSUE TITLE
Make table sortable

### ISSUE THREAD

**Issue by pavel-aicradle** [watsonbox/exportify#62]
It would be nice if the table rows were sortable by column values.

**Comment by watsonbox** [comment]
I agree it's a nice to have, though I'm not quite sure yet how easy it would be to do on the API side.

A glance at the docs makes it seem like doing this directly with the API won't be possible: https://developer.spotify.com/documentation/web-api/reference-beta/#category-playlists.

**Comment by pavel-aicradle** [comment]
That's annoying. You could do a volley of queries to get all the table info for all playlists and then sort, only displaying the 1-20 or whatever range. It shouldn't take more than a couple seconds to fetch and make use of all that information, so UX wouldn't be too bad. It's just annoying to code.

**Comment by watsonbox** [comment]
We could add this in the future, but for now as part of [https://github.com/watsonbox/exportify/milestone/1](the refresh work) I figured that [searching](https://github.com/watsonbox/exportify/issues/19) was the more useful of the two, and so [opened a PR for that](https://github.com/watsonbox/exportify/pull/82) instead.
