### ISSUE TITLE
exported in a PDF

### ISSUE THREAD

**Issue by foeks** [watsonbox/exportify#64]
Can an option be made for the playlist to be exported in a PDF?

**Comment by pavelkomarov** [comment]
You can load the table of values in to a document and save as pdf after download. I'd say wanting pdf output is pretty niche, so this is probably a wontfix.

**Comment by watsonbox** [comment]
@pavel-aicradle Completely agree. We want to keep this tool focused on what it does: exporting data.

When it comes to presentation, there are a bunch of ways that can be done, including PDF, but that would be best in another repository focused on that IMO.
