### ISSUE TITLE
"Export All" not working

### ISSUE THREAD

**Issue by Gahamelas** [watsonbox/exportify#65]
Excellent tool!
It works when I export individual playlists.
However, it doesn't when I try to export all at the same time:
I go to [the website](https://rawgit.com/watsonbox/exportify/master/exportify.html#access_token=BQBT3RMY_l_Q-yTHDRpBqcdwE-cR7A_Dbba5E_5CQb_NAT1eXtosMDDVdGSipV0RJWBfRsATEI1hnf5gEfPGeaK1W1JrjEuMBNswCOdr6TJRJUa-8Xo_RTAQ1TosvxvPM2uHBeTLVbGVfsAjwnQihE9w&token_type=Bearer&expires_in=3600), I click on Export All, but nothing happens.

Thank you.

**Comment by workflow** [comment]
This is the error: 

![image](https://user-images.githubusercontent.com/1276854/88405464-e629a700-ce01-11ea-9ede-1cfbe2db7a39.png)

**Comment by workflow** [comment]
@Gahamelas Looks like this version [here] is working though!

[here]: https://exportify.net/

**Comment by Gahamelas** [comment]
> @Gahamelas Looks like this version [here](https://exportify.net/) is working though!

Thanks!
