### ISSUE TITLE
RawGit is EoL

### ISSUE THREAD

**Issue by issmirnov** [watsonbox/exportify#66]
RawGit seems to be shutting down

![image](https://user-images.githubusercontent.com/5771615/95671483-9dee6b00-0b4c-11eb-82aa-9fcabd932724.png)

Perhaps it would make sense to migrate to Github Pages or some of the other alternatives listed?

 <ul>
      <li><a href="https://www.jsdelivr.com/rawgit">jsDelivr</a></li>
      <li><a href="https://pages.github.com/">GitHub Pages</a></li>
      <li><a href="https://codesandbox.io/">CodeSandbox</a></li>
      <li><a href="https://unpkg.com/">unpkg</a></li>
    </ul>

**Comment by watsonbox** [comment]
Thank you! This was indeed mentioned a long time ago as an alternative approach, and as you say is now quite critical given the status of RawGit. I'll close this one and use https://github.com/watsonbox/exportify/issues/11 as the canonical issue.

Thanks for pointing it out, and proposing other options 👍 .
