### ISSUE TITLE
Add more data to exports

### ISSUE THREAD

**Issue by watsonbox** [watsonbox/exportify#67]
I created this issue as a master issues for others asking for this facility. Let's triage the requests and see what we should add:

* Track year and genre https://github.com/watsonbox/exportify/issues/59
* Genre and Original Album release year https://github.com/watsonbox/exportify/issues/17
* Record label https://github.com/watsonbox/exportify/pull/58
* Popularity https://github.com/watsonbox/exportify/issues/67#issuecomment-723474565

**Comment by pavel-aicradle** [comment]
I'm attempting to port in some of my expanded attributes via #70

**Comment by lesterw1** [comment]
*Popularity* would be fun to add.
When will you update [https://watsonbox.github.io/exportify/](https://watsonbox.github.io/exportify/)? It doesn't seem to have the latest fields yet.

**Comment by watsonbox** [comment]
Hopefully next week.

I'm working on a partial re-write since the tech stack needs refreshing and I'm trying to avoid investing much time in updating the old code, so the plan is to complete that and then look at adding features.

**Comment by pavel-aicradle** [comment]
@lesterw1 #70 has popularity. It's live at exportify.net. Not sure whether @watsonbox is going to straight merge that or just take inspiration from it for this version, but the information is there in the json, and we have the script to pull it out. Shouldn't be too bad.

**Comment by lesterw1** [comment]
Not sure what all of Pavel's changes are but reading the thread sounds like there may be a few small code collision to be resolved. :) Would be great to have at least an interim of [exportify.net](http://exportify.net) or maybe a **/beta** there as I am really looking just to get a good export of all my playlists *with* genre detail (rather than getting an API key, building it, etc., etc. myself). Thanks.

**Comment by watsonbox** [comment]
@lesterw1 I'm not quite sure to completely understand what you're after: it is my understanding that the fork of this repo accessible at https://exportify.net _does_ support genre. The associated repository is https://github.com/pavel-aicradle/exportify.

For this repo, https://github.com/watsonbox/exportify/pull/80 addresses the requests for extra data (with the exception of record label) that I've grouped in this issue. It's just been merged and is available, as per the `README`, at https://watsonbox.github.io/exportify/.

**Note**: to get genre detail you need to select "Include artists data". There's more information on the PR and in the `README`.
