### ISSUE TITLE
exportify.js:308 Uncaught TypeError: Cannot read property 'href' of undefined

### ISSUE THREAD

**Issue by Alex131089** [watsonbox/exportify#7]
All in the title, cannot export using Chrome neither FF, same error : 
exportify.js:308 Uncaught TypeError: Cannot read property 'href' of undefined

Btw, thank you for this export script/ui :)

**Comment by watsonbox** [comment]
Strange.  I just tested with Chrome v44.0.2403.18 beta (64-bit) and Firefox v38.0.5 and both individual exports and zipped export of all playlists worked just fine.

Can you think of anything unusual about your account or setup?  Do you definitely have playlists?  How many?  Have you got zero starred songs?  What versions are you using?  Do you see the error after clicking 'Get Started'?  Do you have a premium account?  Anything else you can think of might help.

**Comment by Alex131089** [comment]
Tried again in "privacy mode" (ie no extensions), same error. I'm with Chrome 43.0.2357.81.
Nothing unusual I think, maybe subscriber to external playlists, but otherwise normal playlists. Playlists are showing (1-20 of 193), I have premium account. I realize I forgot to mention, it happens when I click "Export all". I only tried with one of them and I could export it.
Maybe the API limit ? But it should display an error message instead of doing nothing (I see this error in the js console) ?

**Comment by watsonbox** [comment]
It could well be related to rate limiting.  I haven't got around to adding error messages yet but will try to add this tomorrow.

In the meantime you could always use the 'Network` section of the Chrome developer tools to inspect the last successful Spotify API request to see if the response has status code 429?

**Comment by watsonbox** [comment]
Rate limiting error messages are now properly handled. I'm pretty sure this will be the issue given that you have 193 playlists.  If so I will close this issue and discussion can continue on #6.

**Comment by Alex131089** [comment]
Actually I still have the issue ; I checked the network tab of the debugger (I should have done that in the first place) and there's no error response it seems. I have one playlist with local/imported track, with href=null, but when alone it seems to be exported right so shouldn't be the problem.
I'll try to dig more.

**Comment by Alex131089** [comment]
I'm not able to debug directly in the browser ; maybe you could add a debug print in the console showing the current playlist/call being proceeded by exportify.js:311 (if available)?

**Comment by Alex131089** [comment]
Putting a `console.debug(arguments[0]);` on line 311 (https://github.com/Alex131089/exportify/blob/fix-issue-7/exportify.js#L312), I'm getting this in the debug console : 
[Object, "success", Object]
Datas are in arguments[0][0], should the same check as https://github.com/watsonbox/exportify/blob/master/exportify.js#L82 be applied here ? Or should it handle this case ?

**Comment by Alex131089** [comment]
I have 1 playlist with no songs, it is the problem.
I forked and tried this code https://github.com/Alex131089/exportify/blob/fix-issue-7/exportify.js#L315  : the API call method seems to clean response to only keep the content, but with an empty playlist, an empty thing is returned, thus the error. So, if no data/song returned, here I simply return an empty CSV file.
I'm now hitting the rate limit issue, but not so much an issue :)

**Comment by watsonbox** [comment]
Nice catch thanks for this - I'll sort this bug ASAP.

**Comment by 7720** [comment]
I have downloaded Exportify but cannot export from Sportify to Exportify.....Please tell me HOW
briancotter88@gmail.com
