### ISSUE TITLE
Improve robustness of CSV export

### ISSUE THREAD

**Issue by watsonbox** [watsonbox/exportify#8]
Also add tests?

**Comment by hpincket** [comment]
Hi there,

I wrote a nearly identical site not too long ago. In the process I wrote a csv writing 'library'. It's RFC 4180 compliant and I've tested it a fair amount.

https://github.com/hpincket/csv-writer.js

I know that right now a song that contains a comma causes issues.
Try spotify:track:3sim3k2wSpOdkJQ8xVWZ6A or "What I Said (From "Let It Shine")"

Best,
Hpincket

**Comment by ocram** [comment]
See https://github.com/watsonbox/exportify/pull/35

**Comment by watsonbox** [comment]
Thanks for raising this and sorry for the delay. I'll take a look ASAP.

**Comment by watsonbox** [comment]
Also from https://github.com/watsonbox/exportify/issues/60:

> In exporting a grand playlist of mine I found I couldn't .read_csv in python because the .csv came out mangled. I was able to go through it to find out what was going on: In some cases fields are missing, and then JavaScript seems to move all cells rightward of that one left to fill the gap. In other cases something like an album name can be really long, and it runs over in to the next cell for some reason, pushing everything to the right rightward.

**Comment by ocram** [comment]
The issue https://github.com/watsonbox/exportify/issues/60 explicitly states that the problem was only unescaped values in cells, which is fixed by https://github.com/watsonbox/exportify/pull/35

**Comment by watsonbox** [comment]
@ocram Got it 👌 , I'll check out that PR.

**Comment by watsonbox** [comment]
Merged ✅ . I think that takes care of this issue, but I'd like to add some tests to the repo, and I'm not entirely comfortable with the framework I've got currently set up, so I'll have a play with that too and see if I can do any better before closing this.

**Comment by pavel-aicradle** [comment]
#70 covers this

**Comment by watsonbox** [comment]
> #70 covers this

👌  I was working through from oldest code submissions.

The CSV tests are now present as part of the React dev stack update so I'll close this.

https://github.com/watsonbox/exportify/blob/09f4d08b5bfe3c2ede6105d2e475ae99646e7b4e/src/components/PlaylistTable.test.jsx#L39-L109
