### ISSUE TITLE
Special Characters Are Not Exporting Correctly

### ISSUE THREAD

**Issue by iamtheplauge** [watsonbox/exportify#86]
For example, I exported some Japanese songs and the titles exported as jumbled garbage. Here is a specific example of the Spotify title and what appeared in the export: "高い壁には幾千のドア" ---> "é«˜ã„å£ã«ã¯å¹¾åƒã®ãƒ‰ã‚¢"

I experienced the same with characters with accents. One example from my export was: "Veinte Años" ---> "Veinte AÃ±os"

This definitely used to work, but I haven't used the exporter since those new columns of info were added, "Artist URI", "Album URI", "Explicit", etc. so I don't know exactly when special characters stopped exporting correctly.

**Comment by watsonbox** [comment]
Hi. Thanks for this report.

I'm on OSX and Chrome, and that playlist you mention displays fine in the app, downloads with the correct filename, and the tracks within the export also look good to me.

![Screen Shot 2020-12-08 at 13 08 46](https://user-images.githubusercontent.com/17737/101482150-8f5adf00-3956-11eb-89ac-b4012506f649.png)
![Screen Shot 2020-12-08 at 13 08 52](https://user-images.githubusercontent.com/17737/101482153-8ff37580-3956-11eb-9bf4-f5cbd63f8b16.png)
![Screen Shot 2020-12-08 at 13 10 03](https://user-images.githubusercontent.com/17737/101482275-c3360480-3956-11eb-9c0a-6d0e1003c03b.png)

The exported files are UTF-8 encoded. You'll need to open them with this character encoding.

**Comment by iamtheplauge** [comment]
I'm using Windows 10 and Chrome. I just tested it out again and the same thing happened.

On Spotify:
![image](https://user-images.githubusercontent.com/75485478/101482880-5ce4be00-3925-11eb-8ced-525980ad6e51.png)
On Exportify:
![image](https://user-images.githubusercontent.com/75485478/101482934-7259e800-3925-11eb-9909-0a90b6717d5c.png)
In Excel:
![image](https://user-images.githubusercontent.com/75485478/101483001-8bfb2f80-3925-11eb-9573-d43937872919.png)

**Comment by watsonbox** [comment]
Ah okay you're using Excel. I just did a quick search and found this, for example, but you may need to adjust the process depending on the version of Excel.

https://excel.officetuts.net/en/examples/how-to-import-csv-file-that-uses-utf-8-encoding

**Comment by iamtheplauge** [comment]
Okay, that solved it. It's too bad it adds an extra step to the process, but at least that works. It's weird, opening these CSVs in Excel used to display everything correctly, I wonder what happened. Anyway, thanks for the assistance.

**Comment by watsonbox** [comment]
Okay cool 👍 . The reason for this is the removal of the BOM https://github.com/watsonbox/exportify/pull/32.

That was done for solid technical reasons but I need to look at this again to weigh up those technical reasons against the practicalities such as in your case.

**Comment by iamtheplauge** [comment]
I see, makes perfect sense. Thanks again.
