### ISSUE TITLE
Exporting unavailable tracks

### ISSUE THREAD

**Issue by tcurdt** [watsonbox/exportify#91]
Some tracks are marked as unavailable - but can be seen in Spotify.
Would it be possible to include them in the export somehow?

**Comment by watsonbox** [comment]
Would you be able to give some more information on specifically which tracks you see as unavailable? I know for myself this happens for example when a track is removed (possibly for legal reasons) on the Spotify side.

I'm sure there are other cases of course, but without more information it's hard to comment.

**Comment by tcurdt** [comment]
I can only speculate about the the reasons. But I have plenty of examples where songs or even albums were pulled by the legal owner. Sometimes just to be re-added under a different id. Which leaves the references in my playlists orphaned.
I need to see if I provide the id.
You make it sound rare, which it is not for me at all. There is a setting in the official client to hide them. Maybe you have that enabled?

**Comment by tcurdt** [comment]
Unfortunately I cannot access the ids - but here are a few screenshot examples:

![Screen Shot 2021-02-14 at 14 22 12](https://user-images.githubusercontent.com/13697/107878037-5435d880-6ed0-11eb-904b-1e5b893a9c18.png)

As you can see a single song was removed from the album. And is also grayed out in my playlist.

Here a complete album was removed and later re-added. I bet just the legal rights owner has changed.

![Screen Shot 2021-02-14 at 14 22 39](https://user-images.githubusercontent.com/13697/107878063-8810fe00-6ed0-11eb-9085-610c51180304.png)

![Screen Shot 2021-02-14 at 14 23 15](https://user-images.githubusercontent.com/13697/107878066-8f380c00-6ed0-11eb-9c1c-0cc827cb975a.png)

I hope that makes the problem more tangible?
I basically would love to still have the grayed out information in the export.

**Comment by watsonbox** [comment]
@tcurdt Do my latest changes help at all?

I noticed there was an [issue with local tracks](https://github.com/watsonbox/exportify/issues/93) but there could be other causes too.

**Comment by tcurdt** [comment]
@watsonbox awesome - that seems to work! thanks!
