### ISSUE TITLE
Fix exporting local tracks

### ISSUE THREAD

**Issue by watsonbox** [watsonbox/exportify#93]
Playlists which contain local tracks are not exported properly.

They appear as greyed out in the playlist for other users, but only the last track will appear in the output CSV file due to the missing track ID.

It might be better to use track URIs internally to represent tracks, as they exist for local tracks too.

This could also be related to https://github.com/watsonbox/exportify/issues/91

**Comment by donniesticks** [comment]
Thank you. I was going to ask about this yesterday.

**Comment by watsonbox** [comment]
Ah, good timing!
