### ISSUE TITLE
Duplicate tracks are not exported

### ISSUE THREAD

**Issue by satanic-mechanic** [watsonbox/exportify#94]
In a fairly long playlist (>2k songs), the export skips quite a few songs. In this playlist:
https://open.spotify.com/playlist/0M32G7hgFDhys9fCOZKxa4?si=ovZDc0kET8aHKycOycaoCA
it is skipping 164 of the 2221 songs.

**Comment by watsonbox** [comment]
Thanks for raising this.

It looks like the songs which aren't exported are duplicates, i.e. the same tracks added multiple times to a playlist.

In this case it seems that only the last one is exported.

**Comment by satanic-mechanic** [comment]
Thanks so much for the fix! Is there a charity I can donate to as a gratuity?  Medecins sans Frontieres?
