### ISSUE TITLE
Support for exporting only public playlists

### ISSUE THREAD

**Issue by djmtype** [watsonbox/exportify#95]
Please provide a method for easily exporting public-only playlists.

**Comment by watsonbox** [comment]
Hi, can you please explain exactly what you mean by a "public-only playlist"?

**Comment by djmtype** [comment]
Hey @watsonbox, "public-only playlist" = only the playlists that have a checkmark in the "Public" column.

**Comment by watsonbox** [comment]
Implemented in #171 - [usage details here](https://github.com/watsonbox/exportify?tab=readme-ov-file#advanced-search-syntax).
